force-app/main/default/objects/FieldConditions__c/fields/DeleteCondition__c.field-meta.xml
<CustomField>
    <fullName>DeleteCondition__c</fullName>
    <label>DeleteCondition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FieldConditions__c/fields/HiddenCondition__c.field-meta.xml
<CustomField>
    <fullName>HiddenCondition__c</fullName>
    <label>Hidden Condition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FieldConditions__c/fields/MandatoryCondition__c.field-meta.xml
<CustomField>
    <fullName>MandatoryCondition__c</fullName>
    <label>Mandatory Condition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FieldConditions__c/fields/NewCondition__c.field-meta.xml
<CustomField>
    <fullName>NewCondition__c</fullName>
    <label>NewCondition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FieldConditions__c/fields/ReadOnlyCondition__c.field-meta.xml
<CustomField>
    <fullName>ReadOnlyCondition__c</fullName>
    <label>Read-only Condition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MultiEditCmpController.cls
public with sharing class MultiEditCmpController {
    @AuraEnabled(cacheable=true)
    public static List<FieldConditionsWrapper> getFieldConditions(String objectApiName) {
        List<FieldConditions__c> fieldConditions = [
            SELECT Id, FieldName__c, HiddenCondition__c, ReadonlyCondition__c, NewCondition__c, DeleteCondition__c, MandatoryCondition__c 
            FROM FieldConditions__c WHERE object__c = :objectApiName
        ];

        List<FieldConditionsWrapper> wrappedConditions = new List<FieldConditionsWrapper>();
        for (FieldConditions__c condition : fieldConditions) {
            wrappedConditions.add(new FieldConditionsWrapper(
                condition.Id,
                condition.FieldName__c,
                condition.HiddenCondition__c,
                condition.ReadonlyCondition__c,
                condition.MandatoryCondition__c,
                condition.NewCondition__c,
                condition.DeleteCondition__c
            ));
        }

        return wrappedConditions;
    }

    public class FieldConditionsWrapper {
        @AuraEnabled public String recordId;
        @AuraEnabled public String fieldName;
        @AuraEnabled public String hiddenCondition;
        @AuraEnabled public String readonlyCondition;
        @AuraEnabled public String mandatoryCondition;
        @AuraEnabled public String newRecordCondition;
        @AuraEnabled public String deleteRecordCondition;

        public FieldConditionsWrapper(String recordId, String fieldName, String hiddenCondition, String readonlyCondition, string mandatoryCondition, string newRecordCondition, string deleteRecordCondition) {
            this.recordId = recordId;
            this.fieldName = fieldName;
            this.hiddenCondition = hiddenCondition;
            this.readonlyCondition = readonlyCondition;
            this.mandatoryCondition = mandatoryCondition;
            this.newRecordCondition = newRecordCondition;
            this.deleteRecordCondition = deleteRecordCondition;
        }
    }
}